### Get all customers through api-docs 
GET http://localhost:8080/api-docs HTTP/1.1

### Get customer by _id 
GET http://localhost:8080/api-docs/6334c6ef4e80bb90e8a5ce9c HTTP/1.1

### Add new customer
POST http://localhost:8080/api-docs HTTP/1.1

content-type: application/json

{
    "firstName": "Justin Michael",
    "lastName": "Jenkins",
    "address": "778 E Main St, Beech Island, SC",
    "birthDate": "July 7, 1970",
    "email": "justinmikes@fulfill.net",
    "classesTaken": "",
    "ordersPlaced": "",
    "subscribed": "No"
    }

### GET on Render    
GET https://painterscorner.onrender.com/api-docs HTTP/1.1

### GET by _id on Render 
GET https://painterscorner.onrender.com/api-docs/6329c369d876ca3c2783bea9 HTTP/1.1
 
### Add new customer 
POST http://painterscorner.onrender.com/api-docs HTTP/1.1

content-type: application/json

{
    "firstName": "Justin Michael",
    "lastName": "Jenkins",
    "address": "778 E Main St, Beech Island, SC",
    "birthDate": "July 7, 1970",
    "email": "justinmikes@fulfill.net",
    "classesTaken": "",
    "ordersPlaced": "",
    "subscribed": "Yes"
}